___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [5]:
mylist=np.arange(5,26,5)

#### 3. Generate an array of 5x5 with zeros 

In [32]:
zrr = np.zeros((5,5))
zrr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
zrr = np.ones((4,4),dtype=int)
zrr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [38]:
srr = np.clip(zrr,7,7)
srr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [40]:
drr=np.full((4,4),7)
drr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [42]:
prr=np.arange(2,17,2)
prr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [48]:
grr = np.arange(0,25).reshape(5,5)
grr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [69]:
grr = np.linspace(0,24,num=25).reshape(5,5)
grr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create randomly 5 numbers with numpy

In [79]:
from numpy import random
x = random.randint(1000,size=(1,5))
x

array([[635,   0, 903, 531, 380]])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [81]:
x = random.standard_normal(size=(5,5))
x

array([[ 1.05806483, -0.13659063,  0.60606107, -0.56845355, -1.18293634],
       [-0.80108073,  0.15081731,  0.30000656,  1.44517223, -0.86954306],
       [-1.17522013,  1.38455606, -1.32742214, -0.67689612, -0.47539957],
       [ 1.59661535, -1.31674785, -2.34126033,  1.22251581,  0.3579505 ],
       [ 2.1729326 , -0.19191206, -0.14108526, -0.49218139, -0.15262745]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [82]:
x = random.randint(20,high = 50, size=(3,4))
x

array([[36, 27, 43, 20],
       [41, 41, 46, 23],
       [24, 42, 44, 35]])

#### 13. Reshape the array below with the shape of 6x8

In [87]:
ranarr.reshape(6,8)

NameError: name 'ranarr' is not defined

In [90]:
#the array code deleted itself, cant tell what the numbers were

In [89]:
#the array code deleted itself, cant tell what the numbers were

## Numpy Indexing and Selection


In [110]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [93]:
smat = mat[1:3,1:3] 
smat

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [98]:
smat = mat[:,0]
smat

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [116]:
smat = mat[1::2]
smat

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

#### 17.Assign 77 to every cell in 3rd column.

In [135]:
mat
smat = mat[:,2:3:]
smat[:] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [149]:
bmat = mat[1:2:,0:1:]
cmat = mat[3:4:,1:2:]

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [151]:
fmat = mat[1:4:2,0:4:2]
fmat

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [192]:
mat= np.arange(1,17).reshape(4,4)
smat = np.array([1, 2, 3,4, 5])
a1=np.sum(smat)
lmat = np.array([12,13,14,15,16])
a2=np.sum(lmat)
amat = smat+lmat
dmat = [amat,6,7,8,9]
dmat

[array([13, 15, 17, 19, 21]), 6, 7, 8, 9]

array([1, 2, 4, 5, 6, 8, 9])

#### 21. Get the standard deviation of the result above

In [198]:
np.std(mat)

4.6097722286464435

#### 22. Get the sum of the second column from array above

In [201]:
#print array here
mat
smat = np.sum(mat[:,1:2])
smat

32

32

#### 23. Get the median, mean and std of 3rd row from array above

In [45]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
mat[2]

array([ 9, 10, 11, 12])

In [207]:
#median
med = np.median(mat[2])
med


10.5

In [203]:
#mean
mn = np.mean(mat[2])
mn

10.5

In [206]:
#std
sd = np.std(mat[2])
sd

1.118033988749895

# Pandas Section

In [208]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [209]:
sal=pd.read_csv('Salaries 2.csv')

In [210]:
sal.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [216]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [215]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [224]:
sal['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [227]:
#max
sal['TotalPay'].max()


567595.43

In [230]:
#avg
sal['TotalPay'].mean()

74768.32197169267

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [242]:
dsr = sal[sal.TotalPay > sal.TotalPay.mean()]
dsr['TotalPay'].count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [248]:
AP = sal.where(sal['EmployeeName'] == 'ALBERT PARDINI')
AP['TotalPayBenefits'].max()

335279.91

**Who is the lowest paid person?**

In [264]:
sal['EmployeeName'].where(sal['TotalPay'] == sal['TotalPay'].min())


0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
            ...    
148649          NaN
148650          NaN
148651          NaN
148652          NaN
148653    Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

**What are the unique Jobs in dataset?**

In [265]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [272]:
ap = sal['JobTitle'].value_counts()
ap.tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [274]:
dsr = sal[sal.TotalPay > sal.TotalPay.mean()].where(sal['Year'] == 2012)
dsr['TotalPay'].count()

16716

**How many people have a title of Manager in their jobs?**

In [286]:
#use apply function here
ap = sal['JobTitle'].apply(ap.str.contains('Manager'),)
ap

AssertionError: 

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [298]:
sal.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [73]:
sal_new = sal.iloc[:,[0,1,2,7,8] ]
sal_new.head()

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [305]:
sal_new=sal.loc[:,['EmployeeName','TotalPayBenefits']]
sal_new.head()

EmployeeName  TotalPayBenefits
0     NATHANIEL FORD         567595.43
1       GARY JIMENEZ         538909.28
2     ALBERT PARDINI         335279.91
3  CHRISTOPHER CHONG         332343.61
4    PATRICK GARDNER         326373.19

**Print out the names of the employees who earn more than min, but less than avg**

In [321]:
sa = sal['EmployeeName'].where(sal['TotalPay'] > sal['TotalPay'].min()) 
sb = sal['EmployeeName'].where(sal['TotalPay'] < sal['TotalPay'].mean())
sc = sal.where(sa==sb)
sc

Id   EmployeeName      JobTitle  BasePay  OvertimePay  OtherPay  \
0            NaN            NaN           NaN      NaN          NaN       NaN   
1            NaN            NaN           NaN      NaN          NaN       NaN   
2            NaN            NaN           NaN      NaN          NaN       NaN   
3            NaN            NaN           NaN      NaN          NaN       NaN   
4            NaN            NaN           NaN      NaN          NaN       NaN   
...          ...            ...           ...      ...          ...       ...   
148649  148650.0  Roy I Tillery     Custodian      0.0          0.0       0.0   
148650  148651.0   Not provided  Not provided      NaN          NaN       NaN   
148651  148652.0   Not provided  Not provided      NaN          NaN       NaN   
148652  148653.0   Not provided  Not provided      NaN          NaN       NaN   
148653       NaN            NaN           NaN      NaN          NaN       NaN   

        Benefits  TotalPay  TotalPayBenefits    Year  Notes         Agency  \
0            NaN       NaN               NaN     NaN    NaN            NaN   
1            NaN       NaN               NaN     NaN    NaN            NaN   
2            NaN       NaN               NaN     NaN    NaN            NaN   
3            NaN       NaN               NaN     NaN    NaN            NaN   
4            NaN       NaN               NaN     NaN    NaN            NaN   
...          ...       ...               ...     ...    ...            ...   
148649       0.0       0.0               0.0  2014.0    NaN  San Francisco   
148650       NaN       0.0               0.0  2014.0    NaN  San Francisco   
148651       NaN       0.0               0.0  2014.0    NaN  San Francisco   
148652       NaN       0.0               0.0  2014.0    NaN  San Francisco   
148653       NaN       NaN               NaN     NaN    NaN            NaN   

        Status  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
...        ...  
148649     NaN  
148650     NaN  
148651     NaN  
148652     NaN  
148653     NaN  

[148654 rows x 13 columns]

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___